# You can set these variables from the command line.
DOCS_DIR = docs
SPHINXBUILD = sphinx-build
GRAPHVIZ_DOT = dot
PACKAGE_NAME = src/wax
IPYKERNEL_NAME = python3

# Always rebuild these targets
.PHONY: all

.PHONY: help
help:
	@echo "Usage: make <target>"
	@echo
	@echo "	 act		 Run actions: flake8, mypy, tests"
	@echo "	 flake8		 Run the flake8."
	@echo "	 format		 Format python files with autofloke, isort and black."
	@echo "	 tests		 Run the tests."
	@echo "	 coverage	Generate a coverage report for unit tests."
	@echo "	 docs		Build the documentation in the docs/_build/html/ directory."
	@echo "	 clean		Remove documentation build, coverage and Python stuff."
	@echo "	 release	Create a source distribution in the dist/ directory."
	@echo

.PHONY: autoflake
autoflake:
	autoflake --in-place --remove-all-unused-imports -r $(PACKAGE_NAME)

.PHONY: isort
isort:
	python -m isort --profile black --float-to-top $(PACKAGE_NAME)

.PHONY: black
black:
	python -m black $(PACKAGE_NAME)

.PHONY: format-package
format-package: autoflake isort black

.PHONY: format-notebooks
format-notebooks :
	cd docs/notebooks && $(MAKE) format

# Demo notebooks under notebooks/ are versioned as jupytext .py only.
# Regenerate the .ipynb locally (they are gitignored) before opening them in Jupyter.
# Only the paired sources are synced; plain scripts in notebooks/ are left alone.
PAIRED_NOTEBOOKS = $(shell grep -l 'formats: ipynb' notebooks/*.py)

.PHONY: notebooks
notebooks :
	jupytext --sync -- $(PAIRED_NOTEBOOKS)

.PHONY: clean-notebooks
clean-notebooks :
	rm -f notebooks/*.ipynb

# Notebook outputs are regenerated by the documentation build, so none should ever
# be committed. This fails if one slips through, which is also what keeps absolute
# home paths out of the repository.
.PHONY: check-notebooks
check-notebooks :
	nbstripout --verify docs/notebooks/*.ipynb

.PHONY: strip-notebooks
strip-notebooks :
	nbstripout docs/notebooks/*.ipynb

.PHONY: format
format: format-package format-notebooks

.PHONY: check-format
check-format: format
	git diff
	./build/has_changed.sh

.PHONY: flake8
flake8:
	# stop the build if there are Python syntax errors or undefined names
	python -m flake8 --count --select=E9,F63,F7,F82 --show-source --statistics $(PACKAGE_NAME)
	# all Python files should follow PEP8 (except some notebooks, see setup.cfg)
	python -m flake8 $(PACKAGE_NAME)
	# exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
	# flake8 . --count --exit-zero --max-complexity=10 --statistics


.PHONY: mypy
mypy:
	python -m mypy -p $(PACKAGE_NAME)


.PHONY: tests
tests:
	python -m pytest \
	--doctest-modules \
	-n auto \
	--durations=30 \
	$(PACKAGE_NAME)

.PHONY: coverage
coverage:
	python -m pytest \
	--cov-report xml  \
	--cov-report html  \
	--cov-report term \
	--cov $(PACKAGE_NAME) \
	--doctest-modules \
	-n auto \
	$(PACKAGE_NAME)

.PHONY: docs
docs:
	cd docs && $(MAKE) html

.PHONY: docs-fast
docs-fast:
	sphinx-build -b html -D nb_execution_mode=off docs docs/_build/html

.PHONY: env
env:
	python -m virtualenv venv

.PHONY: release
release:
	uv build

.PHONY: clean-py
clean-py:
	find . \( -name '*.pyc' -o -name '*.py,cover' -o -name '*~' -o -name '*__pycache__' \) -prune -exec rm -rf {} \;
	rm -rf *.egg-info dist

.PHONY: clean-doc
clean-doc:
	rm -rf docs/_build/*

.PHONY: clean-coverage
clean-coverage:
	rm -rf htmlcov/

.PHONY: clean
clean: clean-docs clean-py clean-coverage

.PHONY: distclean
distclean: clean clean-venv

.PHONY: tags
tags: clean
	ctags -e -R --languages=python

.PHONY: ipykernel
ipykernel:
	python -m ipykernel install --user --name $(IPYKERNEL_NAME)

.PHONY: license
license:
	./build/set_license.sh

.PHONY: check-license
check-license: license
	./build/has_changed.sh

.PHONY: run-notebooks
run-notebooks :
	cd docs/notebooks && $(MAKE) run

.PHONY: act
act : flake8 mypy check-license check-format coverage run-notebooks

.PHONY: pre-commit
pre-commit:
	pre-commit run --all
